/**
 * Sandbox module — types shared across all backends.
 *
 * No backend-specific symbols live here. The {@link SandboxBackend} interface is
 * the only abstraction the tool layer depends on; concrete backends (docker,
 * future cloud-run / hosted) implement it independently.
 */

/**
 * Globally-unique identifier for one execution. Generated by the caller and
 * threaded through logs, artifacts, and the result envelope.
 */
export type SandboxExecutionId = string;

/**
 * Caller-supplied identity for attribution. Optional: backends use it for
 * structured logging, tracing, and future per-tenant quotas. It is contextual
 * metadata, NOT a security boundary — filesystem isolation is unchanged.
 */
export type SandboxExecutionIdentity = {
  readonly tenantId: string;
  readonly userId: string;
};

/**
 * Named resource profile. Maps to spec §6 (without the GPU profile, which is
 * out of scope for v1). Each backend interprets cpu/memory limits in its own
 * units; see {@link SandboxResourceProfileConfig}.
 */
export type SandboxResourceProfile = "sandbox-small" | "sandbox-medium" | "sandbox-large";

/**
 * Terminal status of an execution. Matches spec §12.
 *
 * - `succeeded` — process exited 0.
 * - `failed` — process exited non-zero, or raised, or was rejected by validation.
 * - `timeout` — killed because the effective timeout elapsed.
 * - `cancelled` — killed because the caller aborted via `AbortSignal`.
 * - `internal_error` — the backend itself failed (daemon down, image pull, etc.).
 *
 * `policy_denied` from the spec is deferred — there is no policy engine in v1.
 */
export type SandboxStatus = "succeeded" | "failed" | "timeout" | "cancelled" | "internal_error";

/**
 * Structured failure taxonomy. Matches spec §20 (minus the multi-tenant and
 * dependency-policy classes, which are out of scope for v1).
 *
 * `policy_denied`, `network_denied`, `dependency_denied`, and
 * `dependency_install_failed` are intentionally absent — v1 always runs frozen
 * runtime with no network, so there is no decision to deny.
 */
export type SandboxFailureClass =
  | "validation_error"
  | "job_start_failed"
  | "image_pull_failed"
  | "timeout"
  | "python_exception"
  | "nonzero_exit"
  | "artifact_read_failed"
  | "artifact_write_failed"
  | "resource_exhausted"
  | "internal_error";

/**
 * Per-profile resource limits. Values are advisory targets that each backend
 * enforces in its own units (cgroup quotas for Docker, Cloud Run job flags
 * for a future cloud backend).
 */
export type SandboxResourceProfileConfig = {
  readonly profile: SandboxResourceProfile;
  readonly cpuLimit: string;
  readonly memoryLimitMb: number;
  readonly maxTimeoutSeconds: number;
  readonly maxOutputBytes: number;
  readonly maxArtifactBytes: number;
  readonly maxArtifactCount: number;
};

/**
 * A single file produced by the execution. Bytes are loaded eagerly into
 * memory; backends enforce {@link SandboxResourceProfileConfig.maxArtifactBytes}
 * per file and `maxArtifactCount` overall.
 */
export type SandboxArtifact = {
  readonly name: string;
  readonly bytes: Uint8Array;
};

/**
 * Caller-submitted execution request. Backend-agnostic.
 *
 * `inputArtifacts` keys are POSIX-style relative paths; backends reject names
 * containing `..` or absolute paths with a `validation_error`.
 */
export type SandboxRequest = {
  readonly code: string;
  readonly stdin?: string;
  readonly argv?: readonly string[];
  readonly resourceProfile?: SandboxResourceProfile;
  readonly timeoutSeconds?: number;
  readonly inputArtifacts?: ReadonlyMap<string, Uint8Array>;
};

/**
 * Normalized result envelope returned by every backend. Matches spec §12.
 *
 * `stdout` and `stderr` are pre-truncated to the profile's `maxOutputBytes`;
 * the `*Truncated` flags indicate whether truncation occurred. Large outputs
 * must be routed through artifacts by the executed code, not returned inline.
 */
export type SandboxResult = {
  readonly executionId: SandboxExecutionId;
  readonly status: SandboxStatus;
  readonly exitCode: number | null;
  readonly startedAt: string;
  readonly finishedAt: string;
  readonly durationMs: number;
  readonly stdout: string;
  readonly stderr: string;
  readonly stdoutTruncated: boolean;
  readonly stderrTruncated: boolean;
  readonly artifacts: readonly SandboxArtifact[];
  readonly failureClass?: SandboxFailureClass;
  readonly failureMessage?: string;
  readonly retryable: boolean;
  readonly resourceProfile: SandboxResourceProfile;
  readonly backend: string;
};

/**
 * What a backend supports. Used by callers (and tests) to decide whether a
 * backend is appropriate for a workload without inspecting its name.
 */
export type SandboxBackendCapabilities = {
  readonly isolation: "none" | "container" | "cloud";
  readonly supportsArtifacts: boolean;
  readonly supportsAbort: boolean;
};

/**
 * Options passed to {@link SandboxBackend.execute} per call.
 * Truly universal — no backend-specific symbols.
 *
 * `identity` and `traceContext` are optional contextual metadata for logging,
 * tracing, and future per-tenant quotas. They do not change isolation.
 */
export type SandboxExecuteOptions = {
  readonly executionId: SandboxExecutionId;
  readonly signal?: AbortSignal;
  readonly identity?: SandboxExecutionIdentity;
};

/**
 * The contract every sandbox backend satisfies. The tool layer depends on this
 * interface only; concrete backends live in `./backends/`.
 *
 * Implementations must:
 * - Honor {@link SandboxRequest.resourceProfile} limits in their own units.
 * - Honor {@link SandboxExecuteOptions.signal} for cancellation.
 * - Use {@link classifyFailure} so the failure taxonomy stays uniform.
 * - Provide a fresh, isolated workspace per `executionId`.
 * - Log one structured JSON line per execution; never log code, stdin, or full
 *   stdout/stderr.
 *
 * See `sandbox/README.md` for the full "Writing a new backend" checklist.
 */
export type SandboxBackend = {
  readonly name: string;
  readonly capabilities: SandboxBackendCapabilities;
  execute(request: SandboxRequest, options: SandboxExecuteOptions): Promise<SandboxResult>;
};
